// export const USER_SIGNIN_REQUEST = "USER_SIGNIN_REQUEST";
// export const USER_SIGNIN_FAIL = "USER_SIGNIN_FAIL";
// export const USER_SIGNIN_SUCCESS = "USER_SIGNIN_SUCCESS";

export const USER_AUTH_REQUEST = "USER_AUTH_REQUEST";
export const USER_AUTH_FAIL = "USER_AUTH_FAIL";
export const USER_AUTH_SUCCESS = "USER_AUTH_SUCCESS";

export const USER_LOGOUT = "USER_LOGOUT";

export const USER_DETAIL_REQUEST = "USER_DETAIL_REQUEST";
export const USER_DETAIL_FAIL = "USER_DETAIL_FAIL";
export const USER_DETAIL_SUCCESS = "USER_DETAIL_SUCCESS";

export const USER_UPDATE_REQUEST = "USER_UPDATE_REQUEST";
export const USER_UPDATE_FAIL = "USER_UPDATE_FAIL";
export const USER_UPDATE_SUCCESS = "USER_UPDATE_SUCCESS";

export const USER_LIST_REQUEST = "USER_LIST_REQUEST";
export const USER_LIST_SUCCESS = "USER_LIST_SUCCESS";
export const USER_LIST_FAIL = "USER_LIST_FAIL";

export const TOP_SELLER_LIST_REQUEST = "TOP_SELLER_LIST_REQUEST";
export const TOP_SELLER_LIST_SUCCESS = "TOP_SELLER_LIST_SUCCESS";
export const TOP_SELLER_LIST_FAIL = "TOP_SELLER_LIST_FAIL";
